# ____              _  __          __
# |  _ \            | | \ \        / /
# | |_) | __ _ _ __ | | _\ \  /\  / /_ _ _ __ ___
# |  _ < / _` | '_ \| |/ /\ \/  \/ / _` | '__/ _ \
# | |_) | (_| | | | |   <  \  /\  / (_| | | |  __/
# |____/ \__,_|_| |_|_|\_\  \/  \/ \__,_|_|  \___|
# Default configuration file made by LoreWare (robroblore)
# Note: If you ever want to display the '&' symbol in a message, use '&&' instead.