# ____              _  __          __
# |  _ \            | | \ \        / /
# | |_) | __ _ _ __ | | _\ \  /\  / /_ _ _ __ ___
# |  _ < / _` | '_ \| |/ /\ \/  \/ / _` | '__/ _ \
# | |_) | (_| | | | |   <  \  /\  / (_| | | |  __/
# |____/ \__,_|_| |_|_|\_\  \/  \/ \__,_|_|  \___|
# Default configuration file made by LoreWare (robroblore)
# Note: If you ever want to display the '&' symbol in a message, use '&&' instead.
# Permissions: bankware.createdeletePOI, bankware.canReload

messages:
  prefix: "&l&dBankWare ▶ &r"
  bankerInteract: "&2Buna, ma numesc {name}, cu ce te pot ajuta?"

UI:
  bankerTitle: "&2Banca"
  depositItem: "&2Depoziteaza"
  withdrawItem: "&2Retrage"
  infoItem: "&2Informatii"
  infoItemLore:
    - "Sold curent: &2{balance}"
    - "Dobanda: &2{interest}%"
    - "Suma dobanzii: &2{interestAmount}"
    - "Data urmatoarei dobanzi: &2{nextInterestDate}"
