#_____  _     _  __                          ___          __
#|  __ \(_)   | |/ /                         | \ \        / /
#| |  | |_ ___| ' / _ __ ___  _   _ _ __   __| |\ \  /\  / /_ _ _ __ ___
#| |  | | / __|  < | '__/ _ \| | | | '_ \ / _` | \ \/  \/ / _` | '__/ _ \
#| |__| | \__ \ . \| | | (_) | |_| | | | | (_| |  \  /\  / (_| | | |  __/
#|_____/|_|___/_|\_\_|  \___/ \__,_|_| |_|\__,_|   \/  \/ \__,_|_|  \___|
#    Default configuration file made by LoreWare (robroblore)
#    Note: If you ever want to display the '&' symbol in a message, use '&&' instead.
#    Permissions:

messages:
  prefix: "&l&dDisKroundWare ▶ &r"

discord:
  guildID: "1278086361412538421"

  botActivity:
    onePlayer: "1 jucator online!"
    multiplePlayers: "{playerCount} jucatori online!"

  crossChat:
    enabled: true
    channelID: "1335292249944096798"
    minecraftToDiscordMessage: "{player}: {message}"
    discordToMinecraftMessage: "&9&l<Discord>&r {username}: {message}"

  leaveJoinMessages:
    enabled: true
    channelID: "1335292249944096798"
    joinMessage: "{player} a intrat pe server!"
    leaveMessage: "{player} a iesit de pe server!"

  helpop:
    enabled: true
    channelID: "1335693659722616872"
    message: "{player} a trimis un mesaj la staff: {message}"

  commands:
    online:
      noPlayers: "Nu sunt jucatori online."
      playersOn: "Playerii online sunt:" # Followed by a list of online players, each on a new line
