# _____  _     _  __                          ___          __
# |  __ \(_)   | |/ /                         | \ \        / /
# | |  | |_ ___| ' / _ __ ___  _   _ _ __   __| |\ \  /\  / /_ _ _ __ ___
# | |  | | / __|  < | '__/ _ \| | | | '_ \ / _` | \ \/  \/ / _` | '__/ _ \
# | |__| | \__ \ . \| | | (_) | |_| | | | | (_| |  \  /\  / (_| | | |  __/
# |_____/|_|___/_|\_\_|  \___/ \__,_|_| |_|\__,_|   \/  \/ \__,_|_|  \___|
#    Default configuration file made by LoreWare (robroblore)
#    Note: If you ever want to display the '&' symbol in a message, use '&&' instead.
#    Permissions:

messages:
  prefix: "&l&dDisKroundWare ▶ &r"

minecraft:
  link:
    usage: "Foloseste /link <cod> pentru a conecta contul de discord cu contul de minecraft."
    success: "Contul tau de discord {username} a fost conectat cu succes!"

  helpop:
    usage: "Foloseste /helpop <mesaj> pentru a trimite un mesaj la staff."
    message: "{player} a trimis un mesaj la staff:\n{message}"
    sent: "Cererea ta a fost trimisa cu succes!"
    title: "&b&kA&r&bAi primit un raspuns la helpop!&kA"
    subtitle: "&d{staff} ti-a raspuns de pe {platform}!"
    titleDuration: 3 # In seconds, keep in mind there is already 1 second of fade in and 1 second of fade out
    volume: 1.0

  reply:
    fromDiscordMessage: "&9&l<Discord>&r {username} ti-a raspuns:\n{message}"
    fromMinecraftMessage: "{staff} ti-a raspuns la helpop:\n{message}"
    usage: "Foloseste /reply <player> <mesaj> pentru a raspunde la un mesaj."
    noPlayer: "Jucatorul {player} nu este online."
    noThread: "Nu exista niciun helpop de la jucatorul {player}."
    success: "Raspunsul tau catre {player} a fost trimis cu succes!"
    staffToStaff: "{staff} i-a raspuns lui {player}."

  close:
    usage: "Foloseste /close <player> pentru a inchide un ticket."
    success: "Ticketul playerului {player} a fost inchis cu succes!"
    noThread: "Nu exista niciun mesaj de helpop de la jucatorul {player}."
    fromDiscordClose: "&9&l<Discord>&r {username} a inchis ticketul."
    fromMinecraftClose: "{staff} a inchis ticketul."
  
  crossChat:
    message: "&9&l<Discord>&r {username}: {message}"


discord:
  guildID: "1278086361412538421"

  botActivity:
    onePlayer: "1 jucator online!"
    multiplePlayers: "{playerCount} jucatori online!"

  crossChat:
    enabled: true
    channelID: "1335292249944096798"
    message: "{player}: {message}"

  leaveJoinMessages:
    enabled: true
    channelID: "1335292249944096798"
    joinMessage: "{player} a intrat pe server!"
    leaveMessage: "{player} a iesit de pe server!"

  helpop:
    enabled: true
    channelID: "1335693659722616872"
    playerOffline: "Jucatorul {player} nu mai este online!"

  close:
    message: "Ticketul a fost inchis de catre {staff} pe {platform}."

  commands:
    online:
      noPlayers: "Nu sunt jucatori online."
      playersOn: "Playerii online sunt:" # Followed by a list of online players, each on a new line
