#_____  _     _  __                          ___          __
#|  __ \(_)   | |/ /                         | \ \        / /
#| |  | |_ ___| ' / _ __ ___  _   _ _ __   __| |\ \  /\  / /_ _ _ __ ___
#| |  | | / __|  < | '__/ _ \| | | | '_ \ / _` | \ \/  \/ / _` | '__/ _ \
#| |__| | \__ \ . \| | | (_) | |_| | | | | (_| |  \  /\  / (_| | | |  __/
#|_____/|_|___/_|\_\_|  \___/ \__,_|_| |_|\__,_|   \/  \/ \__,_|_|  \___|
#    Default configuration file made by LoreWare (robroblore)
#    Permissions:
