#   _____                  _    __          __
#  / ____|                | |   \ \        / /
# | |     _ __ _   _ _ __ | |_ __\ \  /\  / /_ _ _ __ ___
# | |    | '__| | | | '_ \| __/ _ \ \/  \/ / _` | '__/ _ \
# | |____| |  | |_| | |_) | || (_) \  /\  / (_| | | |  __/
#  \_____|_|   \__, | .__/ \__\___/ \/  \/ \__,_|_|  \___|
#               __/ | |
#              |___/|_|
# Default configuration file made by LoreWare (robroblore)
# Note: If you ever want to display the '&' symbol in a message, use '&&' instead.
# Permissions: cryptoware.canReload, cryptowarew.createdeletePOI

messages:
  prefix: "&l&dCryptoWare ▶ &r"

trader:
  worldForDayCycle: "world"